1. Clean the data
2. Normalize any required columns
3. Encode the categorical data [ use label encoding only for simplicity ]
4. Divide the data into train test split after separating the features from label
5. Train a decision tree [ Sk Learn ] and calculate its score using score() [ find in decision tree documentation of Sk Learn ]

In [271]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [272]:
path='/content/Task_3_dataset.csv'
df=pd.read_csv(path)

In [273]:
df.head(5)


passenger_id  pclass  ...                 home.dest survived
0          1216       3  ...                       NaN        1
1           699       3  ...                   Croatia        0
2          1267       3  ...                       NaN        0
3           449       2  ...      Cornwall / Akron, OH        1
4           576       2  ...  Barre, Co Washington, VT        0

[5 rows x 15 columns]

In [274]:
df.drop(columns=['passenger_id', 'name','ticket'], inplace=True)

In [275]:
df

pclass     sex   age  ...   body                 home.dest  survived
0         3  female   NaN  ...    NaN                       NaN         1
1         3    male  38.0  ...    NaN                   Croatia         0
2         3  female  30.0  ...    NaN                       NaN         0
3         2  female  54.0  ...    NaN      Cornwall / Akron, OH         1
4         2    male  40.0  ...    NaN  Barre, Co Washington, VT         0
..      ...     ...   ...  ...    ...                       ...       ...
845       1    male  55.0  ...    NaN       London / Birmingham         0
846       1    male  58.0  ...  258.0               Buffalo, NY         0
847       2  female  24.0  ...    NaN        Moscow / Bronx, NY         1
848       3  female   3.0  ...    NaN                       NaN         0
849       2    male  52.0  ...   19.0                 Bronx, NY         0

[850 rows x 12 columns]

In [276]:
df.shape

(850, 12)

In [277]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 850 entries, 0 to 849
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   pclass     850 non-null    int64  
 1   sex        850 non-null    object 
 2   age        676 non-null    float64
 3   sibsp      850 non-null    int64  
 4   parch      850 non-null    int64  
 5   fare       849 non-null    float64
 6   cabin      191 non-null    object 
 7   embarked   849 non-null    object 
 8   boat       308 non-null    object 
 9   body       73 non-null     float64
 10  home.dest  464 non-null    object 
 11  survived   850 non-null    int64  
dtypes: float64(3), int64(4), object(5)
memory usage: 79.8+ KB


Clean Data

In [278]:
#finding the NaN values
df.isnull().sum()



pclass         0
sex            0
age          174
sibsp          0
parch          0
fare           1
cabin        659
embarked       1
boat         542
body         777
home.dest    386
survived       0
dtype: int64

In [279]:
#drop cabin, boat, body, home.dest column
df.drop(columns=['cabin', 'boat','body','home.dest'], inplace=True)

In [280]:
df

pclass     sex   age  sibsp  parch     fare embarked  survived
0         3  female   NaN      0      0   7.7333        Q         1
1         3    male  38.0      0      0   8.6625        S         0
2         3  female  30.0      1      1  24.1500        S         0
3         2  female  54.0      1      3  23.0000        S         1
4         2    male  40.0      0      0  13.0000        S         0
..      ...     ...   ...    ...    ...      ...      ...       ...
845       1    male  55.0      0      0  50.0000        S         0
846       1    male  58.0      0      0  29.7000        C         0
847       2  female  24.0      1      0  26.0000        S         1
848       3  female   3.0      1      1  13.7750        S         0
849       2    male  52.0      0      0  13.0000        S         0

[850 rows x 8 columns]

In [281]:
df['pclass'].unique() #cant drop this

array([3, 2, 1])

In [282]:
df['sex'].unique() #cant drop- we need to encode this

array(['female', 'male'], dtype=object)

In [283]:
df['age'].unique() #cant drop- need to fill the NaN values

array([    nan, 38.    , 30.    , 54.    , 40.    , 28.    , 19.    ,
       22.    , 21.    , 27.    , 60.    , 56.    , 20.    , 16.    ,
       48.    , 32.    , 24.    , 25.    , 18.    , 35.    , 42.    ,
       13.    , 29.    , 38.5   , 45.    , 34.    , 57.    ,  2.    ,
       58.    , 46.    , 50.    , 14.    , 23.    , 32.5   ,  6.    ,
       37.    ,  1.    , 36.    , 39.    , 33.    , 26.    , 41.    ,
       14.5   , 47.    , 31.    ,  8.    , 17.    , 49.    , 11.    ,
       55.    , 34.5   , 51.    ,  0.1667, 65.    , 45.5   , 64.    ,
        0.75  , 15.    , 80.    , 43.    ,  3.    , 61.    , 22.5   ,
       40.5   ,  9.    , 10.    , 28.5   , 44.    ,  0.8333, 52.    ,
        7.    , 70.    ,  5.    ,  0.4167, 62.    , 53.    ,  4.    ,
       18.5   ,  0.6667, 60.5   , 55.5   , 67.    , 63.    , 12.    ,
       74.    , 59.    ,  0.9167, 26.5   , 76.    ])

In [284]:
df['sibsp'].unique() #good as it is

array([0, 1, 2, 8, 5, 4, 3])

In [285]:
df['parch'].unique() #good as it is

array([0, 1, 3, 2, 9, 4, 6, 5])

In [286]:
df['fare'].unique()

#we can drop fare

array([  7.7333,   8.6625,  24.15  ,  23.    ,  13.    ,  22.525 ,
         0.    ,   7.775 ,   9.825 , 211.5   ,  76.2917,  83.1583,
        20.25  ,   7.8542,  16.    ,  23.25  ,  55.    ,   8.4583,
        65.    ,   7.8958,   8.05  ,  26.    ,   7.75  ,  21.    ,
         7.2292,  52.    ,  25.925 ,   8.1583,  11.5   ,   7.925 ,
       262.375 ,   7.55  ,   7.25  ,  15.1   , 134.5   ,  30.5   ,
        83.475 ,  15.5792,  69.55  , 153.4625,   7.125 ,  79.2   ,
        10.5   , 120.    , 512.3292,  25.4667,  20.575 ,   9.4833,
        60.    ,  20.525 ,   9.2167,  14.1083, 106.425 ,  26.55  ,
        14.4542,   7.4958,  10.1708,   7.05  , 110.8833,  21.6792,
        32.5   ,  14.4583,  80.    ,   9.5   ,  36.75  , 108.9   ,
         7.7958,   7.225 ,  25.9292, 164.8667,  26.2875,  46.9   ,
        27.7208,   6.4375,  10.7083,  23.45  ,  15.7417,  29.7   ,
        14.    ,  27.75  ,   7.7417,   9.    ,  13.775 , 211.3375,
         8.1125,  12.875 ,  56.4958,  30.    , 151.55  ,  31.2

In [287]:
df.drop(columns=['fare'], inplace=True)
df

pclass     sex   age  sibsp  parch embarked  survived
0         3  female   NaN      0      0        Q         1
1         3    male  38.0      0      0        S         0
2         3  female  30.0      1      1        S         0
3         2  female  54.0      1      3        S         1
4         2    male  40.0      0      0        S         0
..      ...     ...   ...    ...    ...      ...       ...
845       1    male  55.0      0      0        S         0
846       1    male  58.0      0      0        C         0
847       2  female  24.0      1      0        S         1
848       3  female   3.0      1      1        S         0
849       2    male  52.0      0      0        S         0

[850 rows x 7 columns]

In [288]:
df['embarked'].unique() #nan values present

array(['Q', 'S', 'C', nan], dtype=object)

In [289]:
#survival is target variable

In [290]:
df.isnull().sum()

pclass        0
sex           0
age         174
sibsp         0
parch         0
embarked      1
survived      0
dtype: int64

In [291]:
df.dropna(inplace=True)
df.isnull().sum()

#dropping all null values

pclass      0
sex         0
age         0
sibsp       0
parch       0
embarked    0
survived    0
dtype: int64

In [292]:
df


pclass     sex   age  sibsp  parch embarked  survived
1         3    male  38.0      0      0        S         0
2         3  female  30.0      1      1        S         0
3         2  female  54.0      1      3        S         1
4         2    male  40.0      0      0        S         0
5         3    male  28.0      0      0        S         0
..      ...     ...   ...    ...    ...      ...       ...
845       1    male  55.0      0      0        S         0
846       1    male  58.0      0      0        C         0
847       2  female  24.0      1      0        S         1
848       3  female   3.0      1      1        S         0
849       2    male  52.0      0      0        S         0

[675 rows x 7 columns]

In [293]:
#normalise any required coumns
#we will normalise pclass, age
#encode
#we will encode sex and embarked

n=['pclass','age']
m=[]
for i in n:
  m.append(df[i].max())
k=0
for i in n:
  df[i]=df[i]/m[k]
  k=k+1
df



pclass     sex     age  sibsp  parch embarked  survived
1    1.000000    male  0.4750      0      0        S         0
2    1.000000  female  0.3750      1      1        S         0
3    0.666667  female  0.6750      1      3        S         1
4    0.666667    male  0.5000      0      0        S         0
5    1.000000    male  0.3500      0      0        S         0
..        ...     ...     ...    ...    ...      ...       ...
845  0.333333    male  0.6875      0      0        S         0
846  0.333333    male  0.7250      0      0        C         0
847  0.666667  female  0.3000      1      0        S         1
848  1.000000  female  0.0375      1      1        S         0
849  0.666667    male  0.6500      0      0        S         0

[675 rows x 7 columns]

In [294]:
df['sex'] = np.where(df['sex'] == 'male' , 1 , 0 )

In [295]:
df

pclass  sex     age  sibsp  parch embarked  survived
1    1.000000    1  0.4750      0      0        S         0
2    1.000000    0  0.3750      1      1        S         0
3    0.666667    0  0.6750      1      3        S         1
4    0.666667    1  0.5000      0      0        S         0
5    1.000000    1  0.3500      0      0        S         0
..        ...  ...     ...    ...    ...      ...       ...
845  0.333333    1  0.6875      0      0        S         0
846  0.333333    1  0.7250      0      0        C         0
847  0.666667    0  0.3000      1      0        S         1
848  1.000000    0  0.0375      1      1        S         0
849  0.666667    1  0.6500      0      0        S         0

[675 rows x 7 columns]

In [296]:
#encoding of embarked is left
from sklearn.preprocessing import LabelEncoder
# creating initial dataframe
# creating instance of labelencoder
labelencoder = LabelEncoder()
# Assigning numerical values and storing in another column
df['embarked'] = labelencoder.fit_transform(df['embarked'])



In [297]:
df

pclass  sex     age  sibsp  parch  embarked  survived
1    1.000000    1  0.4750      0      0         2         0
2    1.000000    0  0.3750      1      1         2         0
3    0.666667    0  0.6750      1      3         2         1
4    0.666667    1  0.5000      0      0         2         0
5    1.000000    1  0.3500      0      0         2         0
..        ...  ...     ...    ...    ...       ...       ...
845  0.333333    1  0.6875      0      0         2         0
846  0.333333    1  0.7250      0      0         0         0
847  0.666667    0  0.3000      1      0         2         1
848  1.000000    0  0.0375      1      1         2         0
849  0.666667    1  0.6500      0      0         2         0

[675 rows x 7 columns]

In [298]:
X = df.drop('survived' , axis = 1) 
Y = df['survived']

In [299]:
from sklearn import model_selection
X_train , X_test , Y_train, Y_test = model_selection.train_test_split(X , Y ,test_size = 0.3 , shuffle = True , stratify=Y  )

In [300]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [301]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, Y_train)


DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [302]:
print(classifier.predict(sc.transform([[1,1,34,1,3,2]])))

[0]


In [309]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, y_pred)
print(cm)
accuracy_score(Y_test, y_pred)

[[111  12]
 [ 26  54]]


0.812807881773399